version: '3'
services:
    web:
        image: nginx:stable-alpine
        volumes:
        - ./conf.d:/etc/nginx/conf.d
        - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf
        - ./html:/usr/share/nginx/html
        ports:
        - "80:80"
        - "443:443"
        environment:
        - NGINX_HOST=jenkins.hoge.com
        - NGINX_PORT=80
