version: '3.8'
services:
    jenkins:
        image: jenkins/jenkins:latest
        container_name: jenkins
        user: '1000'
        volumes:
            - ./jenkins_home:/var/jenkins_home
        ports:
            # - '8080:8080'
            - '50000:50000'
        networks:
            proxynet: 
        restart: unless-stopped
        environment: 
            - JENKINS_JAVA_OPTIONS=-Djava.awt.headless=true
            - JENKINS_LOG=/var/jenkins_home/logs/jenkins.log
        #command: --enable-future-java
    reverse_proxy:
        image: nginx:latest
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/conf.d:/etc/nginx/conf.d
            #- ./nginx/certbot/conf:/etc/letsencrypt
            #- ./nginx/certbot/www:/var/www/certbot
        ports:
            - "80:80"
            - "443:443"
        networks:
            proxynet:
        restart: always
    certbot:
        image: certbot/certbot
    volumes:
        - ./nginx/certbot/conf:/etc/letsencrypt
        - ./nginx/certbot/www:/var/www/certbot
networks:
        proxynet: 
            name: custom_network
