version: '3'
services:
    jenkins:
        image: jenkins/jenkins:lts 
        container_name: jenkins
        user: '1985601108'
        volumes:
            - /data/jenkins:/var/jenkins_home
        ports:
            - '80:8080'
            - '2000:2000'
        networks:
            - jenkins_network
        restart: unless-stopped
        environment: 
            - JENKINS_SLAVE_AGENT_PORT=2000
            - JENKINS_JAVA_OPTIONS=-Djava.awt.headless=true
            - JENKINS_LOG=/var/jenkins_home/logs/jenkins.log
        #command: --enable-future-java
networks:
    jenkins_network:
